services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=arihotel'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
      - 'PGDATA=/var/lib/postgresql/data/pgdata'
    ports:
      - '5433:5432'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'